using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using UnityEngine.Video;

// Splash variant: dark studio gradient → Spirit Guardian fades in + waves
// (2s) → flies toward camera + covers the screen → fade to black →
// bouncing lime circle takes over → cursive "w" write-on via Animator.
//
// Self-contained — does NOT use SplashSceneController. Generated by
// Tools/ProjectW/10. Create Logo Splash Variant.
public class SplashLogoController : MonoBehaviour
{
    [Header("Spirit Guardian")]
    public Transform robotRoot;
    public Animator robotAnimator;
    [Tooltip("Animator Bool parameter that drives the wave. Rob11 = 'Hello'.")]
    public string waveBoolName = "Hello";
    [Tooltip("How long the wave bool is held true (user spec: 2 seconds).")]
    public float waveDuration = 2.0f;

    [Header("Phase 1 — Robot entrance")]
    public float entranceDuration = 0.6f;
    public float entranceStartScale = 0f;
    public float entranceEndScale = 1.0f;
    public float preWaveHold = 0.2f;

    [Header("Phase 3 — Fly forward / eat the screen")]
    [Tooltip("How long the robot takes to scale up + dolly toward camera.")]
    public float flyForwardDuration = 0.8f;
    [Tooltip("Multiplier on the robot's localScale at the end of the fly-forward.")]
    public float flyForwardEndScaleMultiplier = 5.0f;
    [Tooltip("World-units the robot moves toward the camera during the fly-forward.")]
    public float flyForwardDistance = 1.2f;
    public Camera mainCamera;

    [Header("Phase 4 — Black overlay")]
    [Tooltip("Full-screen black UI Image. Faded in to cover the robot.")]
    public Image blackOverlay;
    public float blackFadeInDuration = 0.4f;
    public float blackHoldDuration = 0.3f;

    public enum LogoRevealMode { LimeBounceAndSpriteSheet, DualVideo }
    [Header("Logo reveal mode")]
    [Tooltip("DualVideo = video-driven reveal. LimeBounceAndSpriteSheet = original procedural lime circle + cursive 'w'.")]
    public LogoRevealMode revealMode = LogoRevealMode.DualVideo;

    public enum VideoSelection { Both, LogoNeonOnly, GreenEnergyOnly }
    [Tooltip("Which of the two videos to play when revealMode = DualVideo.")]
    public VideoSelection videoSelection = VideoSelection.Both;

    [Header("Video reveal (revealMode = DualVideo)")]
    [Tooltip("Logo_Neon video — typically the lime-green dripping logo stroke. Additive-blended over black.")]
    public VideoPlayer logoNeonPlayer;
    public RawImage logoNeonImage;
    [Tooltip("greenEnergy video — the green energy burst. Additive-blended over black, plays simultaneously.")]
    public VideoPlayer greenEnergyPlayer;
    public RawImage greenEnergyImage;
    [Tooltip("Hard cap on how long the video reveal runs. The routine also exits early when all active clips finish playing — whichever happens first.")]
    public float videoRevealMaxDuration = 6.0f;
    [Tooltip("If true, video Play() is called when the black fade-in STARTS (videos buffer + render to RenderTextures while invisible, becoming visible the moment the fade completes). Eliminates the gap between 'robot gone' and 'video on screen'.")]
    public bool startVideosDuringFade = true;

    [Header("Phase 5 — Lime circle bounce")]
    [Tooltip("Lime green UI Image (Knob sprite or generated circle). Scales up to cover the screen.")]
    public RectTransform limeCircle;
    public Image limeCircleImage;
    [Tooltip("Lime green color matching the brand.")]
    public Color limeColor = new Color(0.78f, 1f, 0.32f, 1f);
    [Tooltip("Anchored position where the small circle appears (relative to anchor — defaults to bottom-right corner).")]
    public Vector2 limeStartAnchoredPosition = new Vector2(-200f, 250f);
    public float limeStartSize = 200f;
    [Tooltip("Final diameter — must be > screen diagonal so the circle fully covers the screen at end.")]
    public float limeEndSize = 3000f;
    public float limeBounceDuration = 0.9f;
    [Tooltip("Bouncy-overshoot ease. Default curve has a 1.15× overshoot then settle. Tweak in inspector.")]
    public AnimationCurve limeBounceCurve = new AnimationCurve(
        new Keyframe(0f, 0f, 0f, 4f),
        new Keyframe(0.55f, 1.15f, 0f, 0f),
        new Keyframe(0.75f, 0.95f, 0f, 0f),
        new Keyframe(0.9f, 1.02f, 0f, 0f),
        new Keyframe(1f, 1f, 0f, 0f)
    );
    public float postBouncePause = 0.15f;

    [Header("Phase 6 — Logo write-on (sprite-sheet Animator)")]
    [Tooltip("UI Image whose sprite is animated by the logo Animator.")]
    public Image logoWriteOnImage;
    public Animator logoAnimator;
    [Tooltip("Animator Trigger that starts the write-on clip.")]
    public string logoTriggerName = "Play";
    [Tooltip("Duration of the write-on clip — script holds for this long before transitioning out. The generator sets this from the actual clip length.")]
    public float logoWriteOnDuration = 2.7f;
    public float postLogoHoldDuration = 0.6f;

    [Header("Phase 7 — Completion")]
    public bool notifyFlutterOnComplete = true;
    [Tooltip("Scene to load after splash. Matches the original splash pattern.")]
    public string sceneToLoadAfterSplash = "Bootstrap";
    [Tooltip("Optional second fade-to-black before scene transition. Reuses blackOverlay if null.")]
    public Image finalFadeImage;
    public float finalFadeDuration = 0.3f;

    // Cached state
    private Vector3 _robotStartLocalScale;
    private Vector3 _robotStartLocalPos;

    void Awake()
    {
        if (robotRoot == null) robotRoot = transform;
        if (mainCamera == null) mainCamera = Camera.main;
        if (robotAnimator == null && robotRoot != null)
        {
            robotAnimator = robotRoot.GetComponentInChildren<Animator>();
        }
        // Pre-buffer the videos NOW (Awake runs before the long splash
        // sequence), so by the time we hit the reveal phase ~4-5 seconds
        // later, both players are prepared and Play() starts instantly.
        if (revealMode == LogoRevealMode.DualVideo)
        {
            if (ShouldUseNeon() && logoNeonPlayer != null && !logoNeonPlayer.isPrepared) logoNeonPlayer.Prepare();
            if (ShouldUseEnergy() && greenEnergyPlayer != null && !greenEnergyPlayer.isPrepared) greenEnergyPlayer.Prepare();
        }
    }

    bool ShouldUseNeon() => videoSelection != VideoSelection.GreenEnergyOnly;
    bool ShouldUseEnergy() => videoSelection != VideoSelection.LogoNeonOnly;

    void Start()
    {
        ApplyInitialPose();
        StartCoroutine(PlaySequence());
    }

    void ApplyInitialPose()
    {
        if (robotRoot != null)
        {
            _robotStartLocalPos = robotRoot.localPosition;
            _robotStartLocalScale = robotRoot.localScale;
            // Start hidden — robot scales in during phase 1
            robotRoot.localScale = Vector3.one * entranceStartScale;
        }
        if (robotAnimator != null)
        {
            robotAnimator.enabled = false;
        }
        if (blackOverlay != null)
        {
            var c = blackOverlay.color;
            c.a = 0f;
            blackOverlay.color = c;
            blackOverlay.gameObject.SetActive(true);
        }
        if (limeCircle != null)
        {
            limeCircle.gameObject.SetActive(false);
        }
        if (limeCircleImage != null)
        {
            limeCircleImage.color = limeColor;
        }
        if (logoWriteOnImage != null)
        {
            // Hidden until phase 6
            logoWriteOnImage.gameObject.SetActive(false);
        }
        if (logoNeonImage != null) logoNeonImage.gameObject.SetActive(false);
        if (greenEnergyImage != null) greenEnergyImage.gameObject.SetActive(false);
        if (finalFadeImage != null)
        {
            var c = finalFadeImage.color;
            c.a = 0f;
            finalFadeImage.color = c;
        }
    }

    IEnumerator PlaySequence()
    {
        // Phase 1 — Robot entrance (scale up from 0)
        yield return RobotEntranceRoutine();

        // Phase 2 — Wave
        if (preWaveHold > 0f) yield return new WaitForSeconds(preWaveHold);
        yield return WaveRoutine();

        // Phase 3 — Fly forward, eat the screen
        yield return FlyForwardRoutine();

        // Phase 4 — Cover with black. For DualVideo mode, start the videos
        // playing IN PARALLEL with the fade-in so by the time the black is
        // opaque the videos are already mid-playback and just need their
        // RawImages activated (no perceived delay).
        bool dualVideo = revealMode == LogoRevealMode.DualVideo;
        if (dualVideo && startVideosDuringFade) StartVideoPlayback();

        yield return FadeBlackInRoutine();

        if (dualVideo)
        {
            // Safety: if startVideosDuringFade was off, start them now.
            if (!startVideosDuringFade) StartVideoPlayback();
            // Reveal — the RenderTextures already have live frames, so
            // activating the RawImages cuts straight to playing video.
            RevealVideoImages();
            yield return DualVideoWaitRoutine();
        }
        else
        {
            if (blackHoldDuration > 0f) yield return new WaitForSeconds(blackHoldDuration);
            yield return LimeBounceRoutine();
            if (postBouncePause > 0f) yield return new WaitForSeconds(postBouncePause);
            yield return LogoWriteOnRoutine();
        }
        if (postLogoHoldDuration > 0f) yield return new WaitForSeconds(postLogoHoldDuration);

        // Phase 7 — Notify Flutter + load next scene (under a final fade if available)
        yield return FinalFadeRoutine();
        if (notifyFlutterOnComplete) SendToFlutter.Send("splash_done");
        if (!string.IsNullOrEmpty(sceneToLoadAfterSplash))
        {
            yield return null;
            SceneManager.LoadScene(sceneToLoadAfterSplash, LoadSceneMode.Single);
        }
    }

    IEnumerator RobotEntranceRoutine()
    {
        if (robotRoot == null) yield break;
        float t = 0f;
        float duration = Mathf.Max(0.01f, entranceDuration);
        Vector3 endScale = _robotStartLocalScale * entranceEndScale;
        Vector3 startScale = _robotStartLocalScale * entranceStartScale;
        while (t < duration)
        {
            t += Time.deltaTime;
            float u = Mathf.Clamp01(t / duration);
            // Smoothstep with slight back-ease at start for "popping in"
            float eased = u * u * (3f - 2f * u);
            robotRoot.localScale = Vector3.LerpUnclamped(startScale, endScale, eased);
            yield return null;
        }
        robotRoot.localScale = endScale;
    }

    IEnumerator WaveRoutine()
    {
        if (robotAnimator == null) yield break;
        robotAnimator.enabled = true;
        yield return null; // let the animator init
        if (!string.IsNullOrEmpty(waveBoolName))
        {
            robotAnimator.SetBool(waveBoolName, true);
        }
        yield return new WaitForSeconds(waveDuration);
        if (!string.IsNullOrEmpty(waveBoolName))
        {
            robotAnimator.SetBool(waveBoolName, false);
        }
    }

    IEnumerator FlyForwardRoutine()
    {
        if (robotRoot == null) yield break;
        // Suspend animator so our scale/position changes don't fight it
        if (robotAnimator != null) robotAnimator.enabled = false;

        Vector3 startScale = robotRoot.localScale;
        Vector3 endScale = startScale * flyForwardEndScaleMultiplier;
        Vector3 startPos = robotRoot.localPosition;
        Vector3 endPos = startPos;
        if (mainCamera != null)
        {
            Vector3 toCamWorld = (mainCamera.transform.position - robotRoot.position).normalized;
            // Translate in robotRoot's parent's local space
            Vector3 toCamLocal = robotRoot.parent != null
                ? robotRoot.parent.InverseTransformDirection(toCamWorld)
                : toCamWorld;
            endPos = startPos + toCamLocal * flyForwardDistance;
        }

        float t = 0f;
        float duration = Mathf.Max(0.01f, flyForwardDuration);
        while (t < duration)
        {
            t += Time.deltaTime;
            float u = Mathf.Clamp01(t / duration);
            // Ease-in cubic — accelerates toward camera (gathering momentum)
            float eased = u * u * u;
            robotRoot.localScale = Vector3.LerpUnclamped(startScale, endScale, eased);
            robotRoot.localPosition = Vector3.LerpUnclamped(startPos, endPos, eased);
            yield return null;
        }
        robotRoot.localScale = endScale;
        robotRoot.localPosition = endPos;
    }

    IEnumerator FadeBlackInRoutine()
    {
        if (blackOverlay == null) yield break;
        Color c = blackOverlay.color;
        float t = 0f;
        float duration = Mathf.Max(0.01f, blackFadeInDuration);
        while (t < duration)
        {
            t += Time.deltaTime;
            float u = Mathf.Clamp01(t / duration);
            c.a = u;
            blackOverlay.color = c;
            yield return null;
        }
        c.a = 1f;
        blackOverlay.color = c;
    }

    IEnumerator LimeBounceRoutine()
    {
        if (limeCircle == null) yield break;
        limeCircle.gameObject.SetActive(true);
        limeCircle.anchoredPosition = limeStartAnchoredPosition;
        limeCircle.sizeDelta = new Vector2(limeStartSize, limeStartSize);

        Vector2 startSize = new Vector2(limeStartSize, limeStartSize);
        Vector2 endSize = new Vector2(limeEndSize, limeEndSize);
        Vector2 startPos = limeStartAnchoredPosition;
        Vector2 endPos = Vector2.zero; // center on parent

        float t = 0f;
        float duration = Mathf.Max(0.01f, limeBounceDuration);
        while (t < duration)
        {
            t += Time.deltaTime;
            float u = Mathf.Clamp01(t / duration);
            float curved = limeBounceCurve.Evaluate(u);
            // Size uses bouncy curve. Position uses smoothstep so it slides
            // to center as it expands.
            float posU = u * u * (3f - 2f * u);
            limeCircle.sizeDelta = Vector2.LerpUnclamped(startSize, endSize, curved);
            limeCircle.anchoredPosition = Vector2.LerpUnclamped(startPos, endPos, posU);
            yield return null;
        }
        limeCircle.sizeDelta = endSize;
        limeCircle.anchoredPosition = endPos;
    }

    // Start video playback (one or both per videoSelection). RawImages are
    // NOT activated here — that's done separately by RevealVideoImages so
    // the videos can buffer/render to their RenderTextures invisibly while
    // the black overlay is fading in.
    void StartVideoPlayback()
    {
        if (ShouldUseNeon() && logoNeonPlayer != null)
        {
            logoNeonPlayer.Stop();
            logoNeonPlayer.Play();
        }
        if (ShouldUseEnergy() && greenEnergyPlayer != null)
        {
            greenEnergyPlayer.Stop();
            greenEnergyPlayer.Play();
        }
    }

    // Activate the RawImages so the videos become visible. Frames are
    // already flowing into the RenderTextures from StartVideoPlayback().
    void RevealVideoImages()
    {
        if (ShouldUseNeon() && logoNeonImage != null) logoNeonImage.gameObject.SetActive(true);
        if (ShouldUseEnergy() && greenEnergyImage != null) greenEnergyImage.gameObject.SetActive(true);
    }

    // Wait until the active players finish (or the safety cap fires).
    IEnumerator DualVideoWaitRoutine()
    {
        bool useNeon = ShouldUseNeon();
        bool useEnergy = ShouldUseEnergy();
        float elapsed = 0f;
        float cap = Mathf.Max(0.5f, videoRevealMaxDuration);
        while (elapsed < cap)
        {
            elapsed += Time.deltaTime;
            bool neonDone = !useNeon || logoNeonPlayer == null || !logoNeonPlayer.isPlaying;
            bool energyDone = !useEnergy || greenEnergyPlayer == null || !greenEnergyPlayer.isPlaying;
            // Skip the first frames where isPlaying may not have flipped true yet
            if (elapsed > 0.3f && neonDone && energyDone) break;
            yield return null;
        }
    }

    IEnumerator LogoWriteOnRoutine()
    {
        if (logoWriteOnImage == null) yield break;
        logoWriteOnImage.gameObject.SetActive(true);
        if (logoAnimator != null && !string.IsNullOrEmpty(logoTriggerName))
        {
            logoAnimator.SetTrigger(logoTriggerName);
        }
        yield return new WaitForSeconds(logoWriteOnDuration);
    }

    IEnumerator FinalFadeRoutine()
    {
        var fader = finalFadeImage != null ? finalFadeImage : blackOverlay;
        if (fader == null) yield break;
        // If we're reusing blackOverlay it's already at alpha 1 — bail.
        if (fader == blackOverlay) yield break;
        Color c = fader.color;
        float t = 0f;
        float duration = Mathf.Max(0.01f, finalFadeDuration);
        while (t < duration)
        {
            t += Time.deltaTime;
            float u = Mathf.Clamp01(t / duration);
            c.a = u;
            fader.color = c;
            yield return null;
        }
        c.a = 1f;
        fader.color = c;
    }
}
